name: Update website
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy static site to S3 bucket
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD^..HEAD | xargs -I % sh -c "aws s3 rm s3://testing-git-01/% && aws s3 cp % s3://testing-git-01/%"
        aws s3 sync . s3://testing-git-01 --exclude ".git/*" --exclude ".github/*" --delete
